baseURL = "https://rumlang.org/"
languageCode = "en-us"
title = "The Rum Programming Language"
description = "Rum is an open source programming language that makes it easy to build simple, reliable, and efficient software for statistical computing"
theme = "kube"

[params]
twitter = "rumlangorg"

[[menu.main]]
name = "Playground"
weight = -100
url = "http://play.rumlang.org/"
[[menu.main]]
name = "Legal"
weight = -100
url = "/legal/"