baseURL = "https://rumlang.org/"
languageCode = "en-us"
title = "Rum Language"
description = "Functional language, easily extensible and possible (Lua features with LISP syntax and functional) to be embarked on software Go"
theme = "kube"

[params]
tagline = "rum, rumlang, lisp, clisp, golang, functional"
twitter = "rumlangorg"
lang = "en"
highlightjs = true
footertext = "written by Rum Team"
googleAnalytics = "UA-113963945-1"

[[menu.main]]
name = "Playground"
weight = -100
url = "http://play.rumlang.org/"
[[menu.main]]
name = "Legal"
weight = -100
url = "/legal/"