baseURL = "https://rumlang.org/"
languageCode = "en-us"
title = "The Rum Programming Language"
description = "Rum is an open source programming language that makes it easy to build simple, reliable, and efficient software for statistical computing"
theme = "kube"

[params]
tagline = "rum, rumlang, lisp, clisp, golang"
twitter = "rumlangorg"
lang = "en"
highlightjs = true
footertext = "written by Rum Team"
googleAnalytics = "UA-113963945-1"

[[menu.main]]
name = "Playground"
weight = -100
url = "http://play.rumlang.org/"
[[menu.main]]
name = "Legal"
weight = -100
url = "/legal/"